# Coolify runtime for TAKATAK web and workers.
# MochaHost keeps using deploy/linux/Dockerfile plus server.js.
# Standalone output is intentionally off: the Passenger artifact and
# Prisma JavaScript client expect a full webpack `.next` and node_modules.

FROM node:22.23.2-bookworm-slim AS build

WORKDIR /app

ENV NEXT_TELEMETRY_DISABLED=1
ENV NPM_CONFIG_IGNORE_SCRIPTS=false
ENV NPM_CONFIG_AUDIT=false
ENV NPM_CONFIG_FUND=false

RUN apt-get update \
  && apt-get install -y --no-install-recommends ca-certificates openssl \
  && rm -rf /var/lib/apt/lists/*

COPY package.json package-lock.json .npmrc ./
RUN npm ci --ignore-scripts=false

COPY . .

# Public values are inlined into the client bundle at build time.
# Coolify build arguments must supply them. Do not bake real keys into git.
ARG NEXT_PUBLIC_SUPABASE_URL
ARG NEXT_PUBLIC_SUPABASE_ANON_KEY
ARG NEXT_PUBLIC_APP_URL
ARG NEXT_PUBLIC_UPMIND_ORDER_CONFIG_URL
ARG NEXT_PUBLIC_UPMIND_WIDGET_SCRIPT_URL
ARG NEXT_PUBLIC_UPMIND_DAC_SCRIPT_URL
ARG NEXT_PUBLIC_UPMIND_BRAND_ID
ARG NEXT_PUBLIC_UPMIND_ACCOUNT_ID
ARG NEXT_PUBLIC_UPMIND_CURRENCY
ARG NEXT_PUBLIC_UPMIND_DOMAIN_SEARCH_MODE
ARG NEXT_PUBLIC_TIDIO_PUBLIC_KEY
ARG NEXT_PUBLIC_CRISP_WEBSITE_ID
ARG NEXT_PUBLIC_INTERCOM_APP_ID
ARG NEXT_PUBLIC_HUBSPOT_PORTAL_ID
ARG NEXT_PUBLIC_LIVE_CHAT_PROVIDER

ENV NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL
ENV NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY
ENV NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL
ENV NEXT_PUBLIC_UPMIND_ORDER_CONFIG_URL=$NEXT_PUBLIC_UPMIND_ORDER_CONFIG_URL
ENV NEXT_PUBLIC_UPMIND_WIDGET_SCRIPT_URL=$NEXT_PUBLIC_UPMIND_WIDGET_SCRIPT_URL
ENV NEXT_PUBLIC_UPMIND_DAC_SCRIPT_URL=$NEXT_PUBLIC_UPMIND_DAC_SCRIPT_URL
ENV NEXT_PUBLIC_UPMIND_BRAND_ID=$NEXT_PUBLIC_UPMIND_BRAND_ID
ENV NEXT_PUBLIC_UPMIND_ACCOUNT_ID=$NEXT_PUBLIC_UPMIND_ACCOUNT_ID
ENV NEXT_PUBLIC_UPMIND_CURRENCY=$NEXT_PUBLIC_UPMIND_CURRENCY
ENV NEXT_PUBLIC_UPMIND_DOMAIN_SEARCH_MODE=$NEXT_PUBLIC_UPMIND_DOMAIN_SEARCH_MODE
ENV NEXT_PUBLIC_TIDIO_PUBLIC_KEY=$NEXT_PUBLIC_TIDIO_PUBLIC_KEY
ENV NEXT_PUBLIC_CRISP_WEBSITE_ID=$NEXT_PUBLIC_CRISP_WEBSITE_ID
ENV NEXT_PUBLIC_INTERCOM_APP_ID=$NEXT_PUBLIC_INTERCOM_APP_ID
ENV NEXT_PUBLIC_HUBSPOT_PORTAL_ID=$NEXT_PUBLIC_HUBSPOT_PORTAL_ID
ENV NEXT_PUBLIC_LIVE_CHAT_PROVIDER=$NEXT_PUBLIC_LIVE_CHAT_PROVIDER

RUN test -n "$NEXT_PUBLIC_SUPABASE_URL" \
  && test -n "$NEXT_PUBLIC_SUPABASE_ANON_KEY" \
  && test -n "$NEXT_PUBLIC_APP_URL" \
  && npm run db:generate \
  && npm run build

FROM node:22.23.2-bookworm-slim AS runner

WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV HOST=0.0.0.0

RUN apt-get update \
  && apt-get install -y --no-install-recommends ca-certificates openssl \
  && rm -rf /var/lib/apt/lists/*

COPY --from=build /app /app
RUN chown -R node:node /app

USER node

EXPOSE 3000

HEALTHCHECK --interval=30s --timeout=8s --start-period=40s --retries=3 \
  CMD node -e "fetch('http://127.0.0.1:'+(process.env.PORT||3000)+'/api/health/ready').then((r)=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))"

CMD ["sh", "-c", "exec node node_modules/next/dist/bin/next start -H 0.0.0.0 -p ${PORT:-3000}"]
